### ISSUE TITLE
Replace ramda for your own functions

### ISSUE THREAD

**Issue by mrcode0x0** [Nicasiomarques/restfull-fp-oop#2]
Due to the fact that you are not using such complex things, I don't see the need to use **ramda** ja **curry**, **partial implementation** and **pipe** are simple things to implement without ramda reducing the number of libs we have less **third-party** code to import us follow Below are some suggestions for implementing the above functions.

```js
const pipe = (...fns) => value => fns.reduce((xs, x) => x(xs), value)

// EQ ramda.__
const partialize = (fn, ...args) => fn.bind(null, ...args); 

const curry = function(fn) {
  return function(...args) {
    if (args.length >= fn.length) return fn(...args);
    else {
      return function(...args2) {
        return fn(...args, ...args2);
      }
    }
  }
}

```

Any doubts about the understanding of any implementation do not exist in contacting me if the change suggestion is relevant who knows we can work in collaboration to implement. Sincerely _mrcode0x0_.

**Comment by Nicasiomarques** [comment]
Hi mrcode0x0 thank you very much for the suggestion and I'm glad you took a look at my project it means a lot to me I'll work on these changes they really make sense to me and if you need help if you allow me of course I'll call you so we can trace an idea about it but I'm familiar with the implementations as soon as the PR is ready I will let you know to analyze what can be changed. Thank you so much again
